### ISSUE TITLE
Command palette: fix interactivity

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#102]
Currently you can only interact with the command palette options via the keyboard up/down arrows and ENTER. a user should be able to select a palette option with their mouse as well.

Additionally, it could be a good idea to have the first palette command highlighted/selected by default, similar to how search works. It's an indicator of how they will interact with it.

**Comment by progrium** [comment]
Not quite sure why you can't use mouse, but maybe I just forgot to add a click handler.
