### ISSUE TITLE
Mobile nav enhancement

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#114]
* top nav should be moved to a fixed bottom bar

SIDEBAR
* sidebar should open on top of main panel, not push the main panel to the side
* tapping the "sidebar" icon toggles the sidebar drawer open and closed
* tapping a nav item in the sidebar will close the sidebar and redirect the user to the specified node
* sidebar drawer will scroll if necessary

SEARCH
* search opens up in a modal with a translucent overlay
* search interactions should work similar to sidebar interactions - tap a search result item to navigate to it or tap the search icon in the bottom bar to close search.

style updates (tara can do these later)
* sidebar drawer has an increased font size and padding for bigger tap targets
* search bar will also need a larger font size and tap targets

prototype:
https://www.figma.com/file/bGzEZo0NYHhWGJO95kwF3p/Treehouse-App?node-id=207%3A2585&t=WN6qaMSfuAkDsCyJ-1

**Comment by taramk** [comment]
assigning to myself so i can add mockups

**Comment by taramk** [comment]
@progrium will break down the implementation details, maybe split up into separate tickets

**Comment by progrium** [comment]
Going to use this issue for a rough pass and then minor details can be filed and handled by Dwayne.

- [ ] split out nav component
- [ ] split out panels component
- [ ] create app/mobile component
- [ ] search dialog
- [ ] detect mobile

**Comment by progrium** [comment]
Pushed preliminary implementation. Most minor things can be fixed with css (sizing), but noticing more thought needs to be put into multiple panels, etc.
