### ISSUE TITLE
Command palette search uses ID, not normalized title

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#117]
* you have to type the beginning of the phrase (i.e. for "Create search node" to show up, you have to type "create" - "search" doesn't bring up any results)
* you can't type capital letters (i.e. "Create" does not bring up "Create search node", but "create" does.

http://recordit.co/nqspmP4m7l

**Comment by progrium** [comment]
Wondered why it wasn't working for certain stuff. Made me realize it's searching against its internal ID not its title.

**Comment by taramk** [comment]
i suspected as much, since capitalizing the words wasn't working

**Comment by taramk** [comment]
Probably need to change the property search is looking at (title rather than id) and making it case-insensitive
