### ISSUE TITLE
Making a search node locally breaks the deployed site

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#118]
![image](https://user-images.githubusercontent.com/1813419/235227609-89899d6a-2f0c-4760-9a7e-874ed532eb5c.png)
![image](https://user-images.githubusercontent.com/1813419/235227573-ab538034-1738-46aa-b4fa-b66387881371.png)

To repro: Make a search node locally, then switch to deployed version. Console shows above error and site hangs on loading screen.

**Comment by progrium** [comment]
Closing but @progrium pls confirm
