### ISSUE TITLE
tabs view

### ISSUE THREAD

**Issue by progrium** [treehousedev/treehouse#126]
Figma:
https://www.figma.com/file/bGzEZo0NYHhWGJO95kwF3p/Treehouse-App?type=design&node-id=357%3A5425&t=59W8dlUiykPBL51W-1

* add "View as tabs" option to command palette

* no node handles on tabs
* tab text is editable
* styles should match table styles regarding vertical spacing/padding and header horizontal rule

**Comment by taramk** [comment]
@ArcaTech - this is fairly similar to the table view polish ticket (#210) so maybe do that one first or do them at the same time to share styles. lmk if you have any questions!

**Comment by taramk** [comment]
@ArcaTech moving to the next sprint
