### ISSUE TITLE
Need ability to delete workspace

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#13]
since we removed the root view i think it isn't possible to delete a workspace. right click > Delete workspace from the sidebar?

**Comment by progrium** [comment]
I think we need some time to figure out what a workspace is more deeply. What are workspaces for? What makes one want a new one? What's unique and what's shared across workspaces? I have the assumption we'll have multiple workspaces that could be stored in different places, like different GitHub repositories. So then, would a single repository store multiple workspaces? This also gets into eventual multi-user stuff and permissions. 

So for now maybe it's easiest to just assume you have a single workspace.

**Comment by taramk** [comment]
yeah that seems simplest for now 👍 so instead this ticket should be to enforce a single workspace.

**Comment by taramk** [comment]
closing the issue bc hiding the root node resolves this (until we decide to allow multiple workspaces)
