### ISSUE TITLE
Homepage view?

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#14]
It could be neat to have a homepage/default view that's kind of a card view of all of your workspaces. something like this:

![image](https://user-images.githubusercontent.com/1813419/219451673-518b2cd8-bc22-4cf0-96df-b2ea2823be69.png)

could also show some metadata about the workspace, if/when we find that useful.

**Comment by progrium** [comment]
I like it, can you include any example references that inspired this? Maybe Figma, Google Docs, etc

**Comment by taramk** [comment]
sure, it's a fairly common pattern. if we think it is worth exploring, i will absolutely do more research/a real mockup. since we just decided to stick to a single workspace for now, i'll hold off on this.

**Comment by progrium** [comment]
It'll take a bit to get to multiple workspaces I think. Probably best to just close this for now.
