### ISSUE TITLE
Show visual indicator when search node is collapsed

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#150]
There is currently no visual indication that a search node is collapsed; we are using the same icon as the uncollapsed version. For the collapsed version, let's put a light gray circle around the search icon like we do for standard collapsed nodes. This requires adjusting some sizing.

Changes:

* Search icon should use the [Feather icon](https://feathericons.com/?query=search) at 1.5px stroke width
* Search icon should always be at the size indicated [in Figma](https://www.figma.com/file/bGzEZo0NYHhWGJO95kwF3p/Treehouse-App?type=design&node-id=265%3A4254&t=mA1yq7iVzEDeSmJF-1) (with the default Feather icon frame, the frame size is 11x11px)
* The light gray outer circle that indicates a collapsed node should be increased in size to 15px, as indicated in the Figma link above. This outer circle size applies to a regular node as well as a search node.
* When the outer light gray circle is applied to the search node, the search node icon should be centered within it.

**Comment by progrium** [comment]
This is cool. If we can standardize this enough to make it programmatic (which there is a chance since we're using SVG) it would benefit extension components that provide these icons so they wouldn't have to create this variation, we could just make it work automatically.

**Comment by taramk** [comment]
@progrium i don't see why not. the search node icon and outer circle size should work fine as a template. i would definitely prefer it to be consistent.
