### ISSUE TITLE
Support setting a theme in the UI

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#168]
Figma:
https://www.figma.com/file/bGzEZo0NYHhWGJO95kwF3p/Treehouse-App?type=design&node-id=304%3A4981&t=5fPxLwn5BUAr2zfi-1

* Add "Preferences" link to User Menu
* Preferences link opens a Preferences modal, where the user can change their theme to one of four options: Light, Dark, Sublime, or Sepia
* Selecting a theme in the modal should update the application. However, the change is not saved until the user clicks "Save changes". If the user selects a different theme, it should display while the modal is open, but is reverted if the user clicks "Cancel".

The custom themes are located here:
https://github.com/taramk/taramk.treehouse.sh/tree/main/ext

**Comment by progrium** [comment]
There is no preference/config system so for now just implement the UI with static data and I'll wire it up.
