### ISSUE TITLE
Hitting return mid-node copies contents instead of moving

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#17]
http://recordit.co/zDF3X2MlCe

to repro:

put your cursor in the middle of a node with some text
hit return
the contents after the cursor are copied to a new node below, but they also stay with the existing node. the contents should be moved to the new node, not copied.

**Comment by taramk** [comment]
@progrium - did you test this out...? now when i hit return mid-node it moves the text properly but it leaves a newline on the top node.

http://recordit.co/1bO7FRQFPF

**Comment by progrium** [comment]
I did not test it with multiline nodes. The height calculation needs to be triggered.
