### ISSUE TITLE
Tags + templates

### ISSUE THREAD

**Issue by progrium** [treehousedev/treehouse#206]
- [x] tag component (name)
- [x] detect # to trigger tag picker (new tag, existing tags)
- [x] add tag command, check for template
- [x] templates node, tag template component
- [x] add tag to indexer? special tag field

**Comment by taramk** [comment]
template = tag w/ field associated with it

**Comment by taramk** [comment]
ideally support multiple tabs

**Comment by progrium** [comment]
@taramk Probably some small tweaks and bugs to work out, but it works. It doesn't give you a set place to make templates for tags, but you can turn any node into a template for now. 

First, you can tag nodes by typing "#" in a node, then you can type a new or existing tag name, picking from the popover if you want. It should then remove the tag text in the node and make a tag badge on the right. You can delete a tag by clicking it and hitting backspace. This all works regardless if there are templates.

Now if you create a node using the name of a tag and run the command "Make template" it'll get a new icon and whatever you add under this node will be added to any node you tag with that name from there on. 

Lastly you can search for tags using "#" in the search query. Currently it only lets you do full text search OR a tag query, but you can also add field filters like "#project status:active".

**Comment by jayfresh** [comment]
If you change a template do nodes using the template get their fields updated?

**Comment by taramk** [comment]
@jayfresh not yet, but we will be adding syncing soon! @progrium do we have a more definite estimate?

**Comment by jayfresh** [comment]
Thanks! Ok, so this would work like prefabs (Unity) or prototypes (JS), is that the aim? Rather than each node instance love on independently. I'm not sure which of those I'd prefer, although with the syncing that feels easier to understand and predict

**Comment by progrium** [comment]
Trying for Unity prefab model.
