### ISSUE TITLE
Quick Add - new node triggered after entering first character

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#216]
* open treehouse.sh/demo in a new private window
* open quick add, and type a word
* the first letter will be in the first node, and the rest of the word will be inserted into a second node below the first

i think it's only reproducible when the cache is cleared? quick add seems to save the text that was last entered into it otherwise.

https://share.getcloudapp.com/ApugkWpq

**Comment by taramk** [comment]
jeff thinks it's related to how he is triggering focus on a new node

**Comment by ArcaTech** [comment]
Is this still an issue? I can't reproduce it. I tried in Safari and Firefox, both with a new private window (testing treehouse.sh/demo specifically).

I remember fixing something similar a while back. Maybe this has been taken care of?

**Comment by taramk** [comment]
it was still an issue at the time i made the ticket (3 weeks ago) but i can't reproduce it now either. i'm also not seeing it in my Playwright test, so... yay? i'll close this.
