### ISSUE TITLE
Error logging in with GitHub

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#22]
I had an issue locally so I cleared local storage, and now when I try to log in with GitHub I get an error and the app just hangs.

http://recordit.co/y47pXPPxy4

Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'e.ID')

Similar issue in Chrome but with a different console message:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/1813419/220440856-efabc265-ee4d-4dfa-998e-d324a32c116c.png">

**Comment by progrium** [comment]
this is because of the issue behind #23
