### ISSUE TITLE
TypeError when changing theme

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#228]
go to the top menu > settings > change a theme > click save changes. the following error will appear in the console and the new theme change is not saved:

Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'n.target.closest("form").elements')

**Comment by progrium** [comment]
yes, seems like it was depending on a form in this case and I should have made a separate form tag knowing that we were replacing them at the outer level. i'll fix

**Comment by taramk** [comment]
i didn't even finish adding my description haha so i added it anyway
