### ISSUE TITLE
Deleting a node doesn't delete child nodes

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#25]
Search is showing me stuff I deleted this morning. Jeff says this is because child nodes aren't deleted when you delete a node.

**Comment by progrium** [comment]
Oh, this isn't an indexing issue. When you delete a node it doesn't delete children right now.

**Comment by taramk** [comment]
@progrium so change this bug text to that?

**Comment by progrium** [comment]
Yes I think so
