### ISSUE TITLE
TypeError related to command palette + tags

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#258]
to reproduce:

with **no node selected** (hit ESC or click an empty space in the side nav), open the command palette and choose a command
then go to any node and try to add a tag
console will show a TypeError, you can't add the tag, and the tag menu is empty.

https://share.getcloudapp.com/X6u78GpQ

![Image](https://github.com/treehousedev/treehouse/assets/1813419/2876cc3b-7d47-4d38-95ae-ca4a58ba7d94)

**Comment by progrium** [comment]
this may have been resolved

**Comment by taramk** [comment]
tara to verify
