### ISSUE TITLE
Can't select a theme in Chrome

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#266]
open chrome, open the user menu, choose settings. try to change the theme dropdown. the dropdown closes right away and you are unable to select a different theme.

works fine in safari, still broken in Firefox (#239)

https://share.getcloudapp.com/5zuOLzdN

**Comment by progrium** [comment]
my experience in chrome is slightly different. this is on treehouse.sh btw:
https://recordit.co/8uXcRHBTKC

on treestar.io i don't experience this at all. lol...

are you able to get it to work differently at all when logged in?
