### ISSUE TITLE
Cutting the node should remove it from view

### ISSUE THREAD

**Issue by progrium** [treehousedev/treehouse#274]
This is how text editors typically work - when you cut text, it's immediately removed from view. This gives you feedback that the cutting action took place. In Treehouse, the cut isn't visibly applied until the paste is applied.

To be clear: this is when you select "Cut" from the Node menu

**Comment by progrium** [comment]
Good catch.

**Comment by taramk** [comment]
Jeff says: the node is still there but we will hide it when it's cut. however we hide it during cut, make sure that it's visible when it's moved.
