### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by ognsya** [treehousedev/treehouse#304]
Could the devs please share what is the current status of the project, and how often they plan on working on it?

I opened an issue a couple months ago and haven't got any reply, nor seen much activity since.

Just asking so I can adjust my expectations (as a user) and time investment (as a tester).

Thanks!

**Comment by progrium** [comment]
Treehouse is part of a much bigger project and our small team is putting our effort elsewhere at the moment. The next rev of Treehouse will be very exciting, but it won't be until later this year. Thanks for your support!
