### ISSUE TITLE
add output and run button to CodeBlock view

### ISSUE THREAD

**Issue by progrium** [treehousedev/treehouse#313]
CodeBlocks are currently just containers to display source code, but we want to provide a way for CodeBlocks to optionally be executed by the `defaultExecutor`. For now we'll use `canExecute` to determine if it should have a Run button and output section, something like this mock:

<img width="762" alt="Screenshot 2024-11-11 at 4 22 41 PM" src="https://github.com/user-attachments/assets/6b7a4806-53d9-4da5-9ee8-7b83134f9a88">

Since `execute` is async, Run should update the output area with "Executing {language}..." until it returns with output.

**Comment by lritter79** [comment]
<img width="802" alt="Screenshot 2024-11-15 at 9 19 10 PM" src="https://github.com/user-attachments/assets/33032f0e-fc98-49da-be70-4d2973a4ea88">

**Comment by lritter79** [comment]
Right now we dont care about support for specific language, just the UI. Test eith JS for now for functionality
