### ISSUE TITLE
web: landing page pass

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#43]
- [x] halftone tile shadow to hero image (green)
- [x] "early development" banner
- [x] halftone tile background to grey sections (white 50% opacity)
- [x] "contact us" section above footer with a link to email us (can do this later if we need more time -tk)
- [x] halftone tile background to footer (white 15% opacity)
- [x] add docs and blog links to top nav

**Comment by progrium** [comment]
maybe a banner between hero and features showing/linking latest release and a reminder its under active development

**Comment by taramk** [comment]
per discussion today: “if you are interested in building a specialized note tool with this product, talk to us” - a section with a form

**Comment by taramk** [comment]
@progrium ready for review: https://www.figma.com/file/6EKKAb0mjYISW7jXVElDm5/Treehouse-Website?node-id=114%3A76468&t=IgqQGW7sRW4SdVcp-1

not a major iteration, but adding in the halftones and a couple banners/callouts. let's go over it tomorrow.

**Comment by taramk** [comment]
here is the final halftone asset, the tile size should be 50x50px.

![Image](https://user-images.githubusercontent.com/1813419/227279429-d84616f7-4782-491a-9f14-55a3492e4b10.png)

figma:
https://www.figma.com/file/6EKKAb0mjYISW7jXVElDm5/Treehouse-Website?node-id=114%3A62073&t=qjvIoBGOUBYBzXEQ-1
