### ISSUE TITLE
Add RSS to blog

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#57]

**Comment by taramk** [comment]
not critical, jeff is testing RSS implementations elsewhere first

**Comment by taramk** [comment]
(need to replace static site system with lume)

**Comment by progrium** [comment]
@taramk Try putting `https://treehouse.sh/blog/feed.rss` into MailChimp's feed thing. The site is running a different static site generator, but nothing changes with how to do local dev. The "Latest Posts" sidebar on the blog is generated dynamically now. We can also now easily create a proper index page for the blog. 

The docs changed a little. First, syntax highlighting changed. If there were customizations, they'll probably need to be updated. I think we also had a black background, but we'd have to find a compatible theme for it. One thing that changed is we used to keep the source code blocks in a scrollable element. Now it pushes the page wide. I tried to apply the old fix and it didn't work, so maybe you can take a look.

The left nav menu is now half generated. The way the TOC plugin works is it only generates for the current page, so I have it showing under the right section when the page is open. The top level page nav is still done by hand, but that can be changed to be generated in another pass. It also changed all the headers to links, so I styled them back to headers, but they are still functionally links (you can click them). Not my ideal, but should be fine.
