### ISSUE TITLE
Improve backspace behavior when cursor is at the beginning of a node

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#6]
Expected Behavior:
1. If a node is indented, hitting backspace once should outdent it once. (When we support more levels of indenting, each time they hit backspace it would be outdented once.)
2. If the user hits backspace again, the node contents should be moved up to the previous line, at the end of the node above. 

Actual behavior:
Nothing happens when you try to backspace at the beginning of a node.

FYI, Tana doesn't do #1, but it feels natural to me. Let me know if you disagree.

Video of Tana:
https://recordit.co/EXoN4cDXHA

**Comment by progrium** [comment]
see commit message for specific changes to verify
