### ISSUE TITLE
Menu item for textbox is always "Mark done" regardless of behavior

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#68]
In the node menu, all of my nodes have the item "Mark done" regardless of whether they have a checkbox or not. 

Selecting "Mark done" does the correct context-specific behavior: adding a checkbox, marking it as done, etc.

I'm not sure what the behavior should be if it's already marked done - selecting "Mark done" doesn't do anything in that case.

**Comment by taramk** [comment]
@progrium did we intentionally remove this functionality from the node menu?

**Comment by progrium** [comment]
oh that's why you were saying is stuff gone. yes, I removed non-core node operations from the menu because I was just adding it willy-nilly before. we need to determine criteria for being in menu vs usable via palette.

**Comment by taramk** [comment]
makes sense, that menu was getting quite long. will close this.
