### ISSUE TITLE
Hide root "/" in top navbar when the user is on their workspace home

### ISSUE THREAD

**Issue by taramk** [treehousedev/treehouse#75]
Leave the section, just hide the slash. So if they have multiple panels open they'll still be vertically aligned. If it's feasible, we could only leave the extra vertical spacing when there are multiple panels open. 

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1813419/228013708-56c79a6c-b586-4acd-bb0d-67b2eeb14c6c.png">

**Comment by progrium** [comment]
I think this was even special case code to show a "/", but we can replace that with a "nbsp;"
